{
 "title": "Monitoreo Ambiental - DHT22",
 "description": "Monitoreo de temperatura y humedad - DHT22",
 "tags": [
  "iot",
  "ambiente"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ambiente\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")"
    }
   ]
  },
  {
   "title": "Humedad",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ambiente\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")"
    }
   ]
  },
  {
   "title": "Temperatura actual",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ambiente\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Humedad actual",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ambiente\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> last()"
    }
   ]
  }
 ]
}